# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20160921_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=42),
        ),
    ]
