# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20161006_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='', max_length=42),
        ),
    ]
