# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_auto_20161006_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='img/self.jpg', upload_to='img'),
        ),
    ]
