# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_auto_20161006_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
